# netlify.toml
[build]
  command = """
    if [ ! -f go.mod ]; then
      hugo mod init github.com/yourusername/yourrepo
    fi
    hugo mod get -u
    hugo mod tidy
    hugo --minify
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.0"
  GO_VERSION = "1.24"
