# netlify.toml
[build]
  command = "rm -f go.mod go.sum && hugo mod init github.com/yourusername/yourrepo && hugo mod get github.com/zeon-studio/hugoplate@main && hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.0"
  GO_VERSION = "1.24"
