[build]
  command = """
    rm -f go.mod go.sum
    hugo mod init github.com/silverwis-com/lifeviewer
    hugo mod get github.com/adityatelange/hugo-PaperMod
    hugo --minify
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.0"
  GO_VERSION = "1.24"
