name: Add Hugo Theme
on:
  workflow_dispatch:
jobs:
  add-theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive  # 모든 submodule 재귀적으로 체크아웃
      - name: Remove existing theme completely
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # 기존 정리 로직...
          
      - name: Add hugoplate theme as submodule
        run: |
          git submodule add https://github.com/zeon-studio/hugoplate.git themes/hugoplate
          git submodule update --init --recursive
          git add .
          git commit -m "Add hugoplate theme as git submodule in themes folder"
          git push
