name: Add Hugo Theme
on:
  workflow_dispatch:
jobs:
  add-theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 전체 히스토리 가져오기
          
      - name: Debug current state
        run: |
          echo "=== Current directory structure ==="
          ls -la
          echo "=== Git status ==="
          git status
          echo "=== Submodules ==="
          git submodule status || echo "No submodules"
          echo "=== .gitmodules content ==="
          cat .gitmodules || echo "No .gitmodules file"
          
      - name: Clean workspace
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          echo "Cleaning workspace..."
          
          # .gitmodules 파일이 있으면 모든 submodule 제거
          if [ -f .gitmodules ]; then
            echo "Found .gitmodules, removing all submodules..."
            git submodule foreach --recursive git clean -xfd || true
            git submodule foreach --recursive git reset --hard || true
            git submodule deinit --all -f || true
            git rm .gitmodules || true
          fi
          
          # 모든 hugoplate 관련 항목 제거
          git rm -rf hugoplate || true
          git rm -rf themes/hugoplate || true
          
          # 로컬 파일시스템에서도 제거
          rm -rf hugoplate themes/hugoplate .git/modules
          
          # themes 디렉토리 준비
          mkdir -p themes
          
          echo "Workspace cleaned"
          
      - name: Commit cleanup
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Clean up workspace before adding theme"
            git push
          else
            echo "No changes to commit"
          fi
          
      - name: Add fresh submodule
        run: |
          echo "Adding hugoplate as submodule..."
          git submodule add https://github.com/zeon-studio/hugoplate.git themes/hugoplate
          
          echo "Initializing submodule..."
          git submodule update --init --recursive
          
          echo "Committing changes..."
          git add .
          git commit -m "Add hugoplate theme as submodule"
          git push
          
      - name: Verify installation
        run: |
          echo "=== Verification ==="
          echo "Themes directory:"
          ls -la themes/
          echo "Submodule status:"
          git submodule status
          echo "Hugoplate files:"
          ls -la themes/hugoplate/ | head -10
