name: Add Hugo Theme

on:
  workflow_dispatch:

jobs:
  add-theme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove existing theme folder
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          rm -rf themes/PaperMod
          git add .
          git commit -m "Remove existing PaperMod folder" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Add PaperMod theme as submodule
        run: |
          git submodule add https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod
          git add .
          git commit -m "Add PaperMod theme as git submodule"
          git push

      - name: Verify theme installation
        run: |
          echo "테마 설치 완료!"
          ls -la themes/
          cat .gitmodules
